"use client";
import { createContext, useContext, useState } from "react";

export type Lang = "th" | "en";

const translations = {
  th: {

    // game card
    playNow: "เล่นเลย",
    viewDetails: "ดูรายละเอียด",
    startFrom: "เริ่มต้นที่",
    availablePackages: "แพ็กเกจที่มีให้เลือก",
    package: "แพ็กเกจ",
    price: "ราคา",
    buyNow: "ซื้อเลย",


    // Footer
    footerAboutUs: "เกี่ยวกับเรา",
    footerAboutDesc: "CYBERPAY คือแพลตฟอร์มเติมเกมและซื้อไอเทมออนไลน์ที่เชื่อถือได้ ให้บริการรวดเร็วและปลอดภัย",
    footerContact: "ติดต่อ",
    footerEmailLabel: "อีเมล",
    footerTelLabel: "โทร",
    footerPaymentMethods: "ช่องทางชำระเงิน",
    footerBankTransfer: "ธนาคาร/โอนเงิน",
    footerCreditCard: "บัตรเครดิต/เดบิต",
    footerLegalSocial: "ข้อกำหนด & โซเชียล",
    footerTerms: "ข้อตกลงการใช้บริการ",
    footerPrivacy: "นโยบายความเป็นส่วนตัว",
    footerTrueMoney: "ทรูมันนี่ วอลเล็ท",
    footerPromptPay: "พร้อมเพย์",
    //Header

    headerHome: "หน้าแรก",
    headerGames: "เกม",
    headerTopUp: "เติมเงิน",
    headerVip: "VIP",
    headerSupport: "ช่วยเหลือ",
    // search page
    search: "ค้นหาเกม...",
    noGamesFound: "ไม่พบเกมที่ค้นหา",


    // Common
    platform: "แพลตฟอร์มเติมเกมอันดับ 1",
    fast: "เติมไว",
    fastDesc: "รับไอเทมภายใน 1-5 นาที",
    safe: "ปลอดภัย 100%",
    safeDesc: "ระบบความปลอดภัยระดับสูง",
    support: "ซัพพอร์ต",
    supportDesc: "ทีมงานพร้อมช่วยเหลือ",
    always: "24/7",
    alwaysDesc: "บริการตลอด 24 ชั่วโมง",
    showMore: "ดูเพิ่มเติม",
    Success: "สำเร็จ!",
    Topupinfo: "ข้อมูลการเติมเงิน",
    Choosepackage: "เลือกแพ็กเกจที่ต้องการ",
    
    // Game Top-up Page
    loadingGame: "กำลังโหลดเกม...",
    gameNotFound: "ไม่พบเกม",
    failedLoadGame: "ไม่สามารถโหลดเกมได้",
    pleaseSelectPackage: "กรุณาเลือกแพ็กเกจ",
    emailRequired: "Email เป็นส่วนบังคับสำหรับใบเสร็จ",
    invalidEmail: "กรุณาป้อน Email ที่ถูกต้อง",
    failedCreateOrder: "ไม่สามารถสร้างคำสั่งซื้อได้",
    orderCreatedSuccess: "คำสั่งซื้อของคุณได้รับการสร้างแล้ว",
    goToAccount: "ไปยังบัญชี",
    orderType: "ประเภทการสั่ง",
    alreadyLoggedIn: "✓ เข้าสู่ระบบแล้ว",
    buyWithoutLogin: "ซื้อโดยไม่เข้าสู่ระบบ",
    switchToMember: "เปลี่ยนไปรูปแบบสมาชิก",
    discountCoupon: "คูปองส่วนลด",
    enterCouponCode: "ป้อนรหัสคูปอง",
    useCoupon: "ใช้",
    applyCouponSuccess: "✓ ใช้คูปอง {code} ประหยัด {discount}%",
    tryCoupons: "ลองใช้: SAVE10, SAVE20, WELCOME",
    orderSummary: "สรุปการสั่ง",
    selectedPackage: "แพคเกจที่เลือก",
    noSelection: "ยังไม่มีการเลือก",
    priceLabel: "ราคา:",
    discountLabel: "ส่วนลด ({discount}%):",
    totalLabel: "รวม:",
    emailForReceipt: "อีเมลสำหรับใบเสร็จ",
    receiptNote: "ใบเสร็จจะถูกส่งไปที่อีเมลนี้",
    orderButton: "สั่ง",
    processing: "กำลังประมวลผล...",
    selectPackageHint: "คลิกเลือกแพคเกจเพื่อเริ่มสั่ง",
    enterCouponError: "กรุณาป้อนรหัสคูปอง",
    invalidCouponError: "รหัสคูปองไม่ถูกต้อง",
    needAtLeastFields: "กรุณากรอกข้อมูลให้ครบถ้วน",

    Topup: "เติมเงิน",
    
    
    
    
    login: "เข้าสู่ระบบ",
    register: "สมัครสมาชิก",
    noAccount: "ยังไม่มีบัญชี?",
    forgot: "ลืมรหัสผ่าน?",
    email: "Email",
    password: "Password",
    divider: "หรือ",
    google: "Google",
    facebook: "Facebook",
    logoDesc: "เข้าสู่ระบบเพื่อเติมเกมได้ทันที",
    errorEmpty: "กรุณากรอก Email และ Password",
    errorEmail: "รูปแบบ Email ไม่ถูกต้อง",
    errorPassword: "รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร",
    errorLogin: "Email หรือรหัสผ่านไม่ถูกต้อง",
    success: "เข้าสู่ระบบสำเร็จ",
    // Support Page
    supportTitle: "ศูนย์ช่วยเหลือ",
    supportSubtitle: "ค้นหาคำตอบด้วยตนเอง หรือติดต่อทีมงานได้ตลอด 24 ชม.",
    faqTitle: "คำถามที่พบบ่อย (FAQ)",
    allCategories: "ทั้งหมด",
    noFaqFound: "ไม่พบคำถามในหมวดนี้",
    videoTitle: "วิดีโอแนะนำการใช้งาน",
    videoPlaceholder: "วิดีโอแนะนำขั้นตอนการเติมเงินและใช้งานระบบ — เร็วๆ นี้",
    contactTitle: "ช่องทางติดต่อเจ้าหน้าที่",
    contactSubtitle: "หาก FAQ ไม่สามารถแก้ปัญหาได้ สามารถติดต่อทีมงานผ่านช่องทางด้านล่าง",
    stillHaveQuestion: "หากยังมีข้อสงสัย?",
    createTicket: "สร้างตั๋ว",
    // Create Ticket Page
    back: "กลับ",
    createTicketTitle: "ติดต่อฝ่ายบริการลูกค้า",
    selectProblem: "เลือกประเภทปัญหา",
    selectProblemPlaceholder: "เลือกประเภทปัญหา",
    userId: "รหัสคำสั่งซื้อ",
    userIdPlaceholder: "",
    userIdHelper: "รหัสคำสั่งซื้อที่ได้รับหลังชำระเงิน",
    paymentMethod: "วิธีการชำระเงิน",
    paymentMethodPlaceholder: "",
    paymentMethodHelper: "วิธีการชำระเงินที่คุณใช้ระหว่างการซื้อ",
    emailPlaceholder: "example@gmail.com",
    emailHelper: "อีเมลที่คุณใช้ในการลงทะเบียนหรือที่สามารถติดต่อกลับได้",
    description: "มีอะไรผิดปกติไหม",
    descriptionPlaceholder: "ให้รายละเอียดเกี่ยวกับสิ่งที่คุณกำลัง...",
    descriptionHelper: "โปรดให้ข้อมูลเพิ่มเติมที่สามารถช่วยให้เราแก้ไขปัญหาได้ ยิ่งคุณให้รายละเอียดมากเท่าไหร่ ก็ยิ่งจะเป็นการแก้ไขที่รวดเร็วยิ่งขึ้นเท่านั้น",
    imageUpload: "รูปภาพเพิ่มเติม",
    optional: "(ถ้ามี)",
    dragDrop: "ลากและวางรูปภาพหรือ",
    selectImage: "เลือกรูปภาพ",
    supportedFormats: "รูปแบบที่รองรับ: PNG, JPG, JPEG",
    infoText: "ภาพหน้าจอการโอนเงิน หรือ ไอดีผู้ใช้ในเกม จะช่วยให้เราสามารถแก้ไขปัญหาได้เร็วขึ้น",
    submit: "สร้างตั๋ว",
    successTitle: "สร้างตั๋วแล้ว",
    successMessage: "เราจะตรวจสอบปัญหาและแก้ไขโดยเร็วที่สุด",
    successSubMessage: "คุณจะได้รับการอัปเดตเพิ่มเติมทางอีเมล",
    viewTicket: "ดูตั๋ว",
    backToSupport: "กลับไปที่ช่วยเหลือ",
    fillAllFields: "กรุณากรอกข้อมูลให้ครบถ้วน",
    invalidFileType: "กรุณาอัปโหลดไฟล์ภาพเท่านั้น (PNG, JPG, JPEG)",
    problemTypes: {
      "missing-payment": "แจ้งการชำระเงินไม่เข้า",
      "incorrect-amount": "แจ้งจำนวนไอเทมไม่ถูกต้อง",
      "wrong-user-id": "User ID หรือ Server ผิด",
      "payment-gateway": "ปัญหาช่องทางชำระเงิน",
      "account-issue": "ปัญหาบัญชีผู้ใช้",
      "other": "อื่นๆ",
    },
    // FAQ Categories
    faqCategories: {
      topup: "การเติมเงิน",
      payment: "การชำระเงิน",
      security: "ความปลอดภัย",
      vip: "VIP & โปรโมชั่น",
      problem: "แก้ปัญหา",
      general: "ทั่วไป",
    },
    // Ticket Listing
    ticketsTitle: "ตั๋วความช่วยเหลือ",
    sortNewest: "ใหม่สุด",
    sortOldest: "เก่าสุด",
    noTickets: "ยังไม่มีตั๋วความช่วยเหลือ",
    noTicketsDesc: "เมื่อคุณสร้างตั๋ว จะแสดงที่นี่",
    statusInQueue: "รอดำเนินการ",
    statusActive: "กำลังดำเนินการ",
    statusClosed: "ปิดแล้ว",
    createdOn: "สร้างเมื่อ",
    // Ticket Detail
    ticketDetail: "รายละเอียดตั๋ว",
    statusLabel: "สถานะ",
    typeYourMessage: "พิมพ์ข้อความ...",
    send: "ส่ง",
    closeTicket: "ปิดตั๋ว (แก้ไขแล้ว)",
    attachments: "ไฟล์แนบ",
    actions: "การดำเนินการ",
    ticketClosedMsg: "ตั๋วนี้ถูกปิดแล้ว",
    ticketClosedDesc: "หากต้องการสอบถามเพิ่มเติม กรุณาสร้างตั๋วใหม่",
    confirmCloseTitle: "ยืนยันการปิดตั๋ว",
    confirmCloseDesc: "คุณแน่ใจหรือไม่ว่าต้องการปิดตั๋วนี้? การดำเนินการนี้ไม่สามารถยกเลิกได้",
    confirmClose: "ยืนยัน",
    cancelClose: "ยกเลิก",
    fileTooLarge: "ไฟล์ต้องมีขนาดไม่เกิน 5MB",
    invalidAttachType: "รองรับเฉพาะไฟล์ .jpg, .png, .pdf เท่านั้น",
    attachFile: "แนบไฟล์",
    sidebarMyAccount: "บัญชีของฉัน",
    sidebarBalance: "ยอดคงเหลือ",
    sidebarOrders: "คำสั่งซื้อ",
    sidebarTickets: "ตั๋ว",
    sidebarSettings: "การตั้งค่า",
    // Account Overview
    accountOverview: "Account Overview",
    home: "หน้าแรก",
    myAccount: "บัญชีของฉัน",
    currentLevel: "ระดับปัจจุบันของคุณ",
    progressLabel: "ความคืบหน้าการเลื่อนระดับ",
    viewVipDetail: "ดูรายละเอียด VIP",
    availableBalance: "AVAILABLE BALANCE",
    topUp: "เติมเงิน",
    transfer: "ดำเนินการโอนเงิน",
    lastUpdated: "อัปเดตล่าสุด เมื่อคู่ที่ผ่านมา",
    transactionHistory: "ประวัติการทำรายการ",
    verified: "VERIFIED",
    // Balance / Top-up Page
    topupProcess: "ดำเนินการเติมเงิน",
    selectPaymentMethod: "เลือกช่องทางการชำระเงิน",
    selectTopupAmount: "ระบุจำนวนเงินที่ต้องการเติม",
    customAmountPlaceholder: "ขั้นต่ำ 20.00",
    
    paymentMethodLabel: "วิธีชำระเงิน",
    topupAmountLabel: "ยอดเติมเงิน",
    feeLabel: "ค่าธรรมเนียม",
    
    confirmTopup: "ยืนยันการทำรายการ",
    topupNote: "ยอดเงินจะถูกเติมเข้าบัญชีของคุณโดยอัตโนมัติ หลังจากการชำระเงินสำเร็จ สำหรับ PromptPay อาจใช้เวลาสูงสุด 5 นาที",
    topupHistory: "ประวัติการเติมเงิน",
    dateTime: "วันที่ / เวลา",
    statusSuccess: "สำเร็จ",
    statusFailed: "ไม่สำเร็จ",
    // Payment Flow Modal
    qrScanInstruction: (method: string) => `สแกน ${method} QR Code ด้านล่างเพื่อชำระเงิน`,
    qrAmount: "จำนวนเงิน",
    qrExpiry: "หมดอายุ",
    qrRef: "รหัสอ้างอิง",
    qrScanHint: "สแกนคิวอาร์ เพื่อทำรายการ (ภายในผู้ให้บริการเดิม)",
    qrSaveBtn: "บันทึกรูป QR Code",
    qrNote: (method: string) => `หมายเหตุ: ใช้ ${method} QR Code แสกนเพื่อทำรายการเท่านั้น`,
    qrTimeLeft: "คงเหลือ 3 นาทีในการสแกน QR",
    qrMinimize: "ย่อกลับ",
    qrContactSupport: "ติดต่อฝ่ายสนับสนุน",
    qrPaymentProblem: "หากมีปัญหาในการชำระเงิน กรุณา",
    processingTitle: "กำลังตรวจสอบการชำระเงิน",
    processingDesc: "ระบบกำลังยืนยันรายการกับธนาคาร/ผู้ให้บริการ อาจใช้เวลา 10 - 30 วินาที",
    processingWarning: "กรุณาอย่าปิดหรือรีเฟรชหน้านี้",
    processingRefId: "หมายเลขอ้างอิง",
    paymentSuccessTitle: "ยืนยันการชำระเงิน",
    paymentSuccessDesc: "การทำธุรกรรมสำเร็จ และขณะนี้กำลังดำเนินการจัดส่ง",
    successEmailNote: "คุณจะได้รับอีเมล",
    successEmailNote2: "ยืนยันว่าสินค้าของคุณได้ถูกจัดส่งแล้ว",
    txItem: "รายการ",
    txChannel: "ช่องทาง",
    txTime: "เวลาทำรายการ",
    txRefId: "รหัสอ้างอิง (Tx ID)",
    txTotalPaid: "ยอดที่ชำระทั้งหมด",
    txTotalDue: "ยอดที่ต้องชำระ",
    backToHome: "กลับสู่หน้าหลัก",
    viewReceipt: "ดูใบเสร็จ / ดาวน์โหลด",
    haveIssue: "มีปัญหาใช่ไหม",
    failedTitle: "ชำระเงินไม่สำเร็จ",
    failedDesc: "เกิดข้อผิดพลาดในการทำรายการ สามารถลองทำรายการใหม่อีกครั้ง หรือลองทดสอบภายหลัง",
    retryPayment: "ลองทำรายการใหม่อีกครั้ง",
    contactSupport: "ติดต่อศูนย์บริการลูกค้า",
    promptpayDesc: "สแกน QR Code เพื่อชำระเงินได้เลย",
    truemoneyDesc: "ชำระผ่านแอปพลิเคชัน",
    recentOrders: "ซื้อล่าสุด",
    viewAll: "ดูทั้งหมด",
    viewAllHistory: "VIEW ALL HISTORY",
    general: "ทั่วไป",
    personalInfo: "ข้อมูลส่วนตัว",
    editProfile: "แก้ไขโปรไฟล์",
    orderHistory: "ประวัติการสั่งซื้อ",
    searchOrders: "ค้นหาเลขที่คำสั่งซื้อ",
    orderDate: "วันที่",
    orderName: "ชื่อรายการคำสั่งซื้อ",
    orderId: "ไอดีคำสั่งซื้อ",
    viewDetail: "รายละเอียด",
    // Order Detail
    backToOrders: "กลับไปที่รายการ",
    orderTitle: "คำสั่งซื้อ",
    orderCreatedAt: "ทำรายการเมื่อ",
    orderStatusSuccess: "จัดการคำสั่งซื้อแล้ว",
    orderStatusFailed: "ชำระเงินไม่ครบ",
    orderProductInfo: "ข้อมูลสินค้าและตัวละคร",
    orderTopupDetail: "รายละเอียดการเติม",
    orderProduct: "สินค้า",
    orderUserId: "User ID (OpenID)",
    orderServer: "เซิร์ฟเวอร์",
    orderPaymentChannel: "ช่องทางการชำระเงินที่ใช้",
    orderPaymentFailed: "สถานะ: ชำระไม่สำเร็จ",
    orderVerified: "รายการได้รับการตรวจสอบความเรียบร้อยแล้ว",
    orderProductPrice: "ราคาสินค้า",
    orderNetTotal: "ยอดชำระสุทธิ",
    orderNetTotalSuccess: "ยอดชำระสุทธิ (สำเร็จ)",
    orderCheckTitle: "ตรวจสอบความเรียบร้อย",
    orderCreateTicket: "🎫 สร้างตั๋วคุยกับ Admin",
    orderCreateTicketNote: "หากไม่ได้รับสินค้าหรือมีปัญหา",
    orderPendingTitle: "มียอดค้างชำระ",
    orderPendingDesc: "ระบบตรวจสอบพบว่ายอดโอนของคุณไม่ตรงกับที่ตั้งไว้ โปรดติดต่อ Admin เพื่อส่งสลิปยืนยัน",
    orderCreateTicketBtn: "สร้างตั๋วคุยกับ Admin",
    orderNotFound: "ไม่พบคำสั่งซื้อ",
    orderStatusSuccessLabel: "จัดการคำสั่งซื้อแล้ว",
    orderStatusPending: "รอดำเนินการ",
    vipPrivileges: "VIP & สิทธิพิเศษ",
    accountSettings: "ตั้งค่าบัญชี",
    logout: "ออกจากระบบ",
    // VIP Tier Details
    backToOverview: "กลับไปหน้าภาพรวม",
    yourCurrentLevel: "ระดับปัจจุบันของคุณ",
    vipTierDetails: "VIP TIER DETAILS",
    statusOverview: "STATUS OVERVIEW",
    highestRank: "HIGHEST RANK",
    infoHighest: "🏆 คุณอยู่ในระดับสูงสุดแล้ว สิทธิพิเศษทั้งหมดพร้อมใช้งาน",
    infoLower: (tier: string) => `✅ คุณได้รับสิทธิพิเศษของ ${tier} แล้ว`,
    infoNeedDiamonds: (amount: string, tier: string) =>
      `💎 คุณต้องการอีก ${amount} Diamond เพื่อเลื่อนระดับเป็น ${tier} และรับสิทธิพิเศษเพิ่มเติม`,
    allTierDetails: "รายละเอียดการเลื่อนระดับทั้งหมด",
    tierBenefits: "สิทธิพิเศษประจำระดับ",
    tierCondition: "เงื่อนไขระดับ",
    minDiamondsText: (amount: string) => `สะสม Diamond ขั้นต่ำ ${amount} เพื่อเข้าสู่ระดับนี้`,
    nextTierText: (amount: string) => `เลื่อนระดับถัดไปที่ ${amount} Diamond`,
    // VIP Benefits
    vipBenefits: {
      vip1: [
        "ส่วนลดค่าเติมเกม 2% ทุกรายการ",
        "รับ Diamond โบนัส 5% เมื่อเติมครบ ฿100",
        "แจ้งเตือนโปรโมชันผ่านอีเมล",
      ],
      vip2: [
        "ส่วนลดค่าเติมเกม 5% ทุกรายการ",
        "รับ Diamond โบนัส 10% เมื่อเติมครบ ฿100",
        "ช่องทาง Support ด่วน (ตอบภายใน 2 ชม.)",
        "เข้าถึงโปรโมชันพิเศษก่อนสมาชิกทั่วไป",
      ],
      vip3: [
        "ส่วนลดค่าเติมเกม 10% ทุกรายการ",
        "รับ Diamond โบนัส 20% เมื่อเติมครบ ฿100",
        "ช่องทาง Support ด่วนสุด (ตอบภายใน 30 นาที)",
        "เข้าถึงโปรโมชันและไอเทมพิเศษก่อนใคร",
        "รับของรางวัลพิเศษทุกเดือน",
        "ไม่มีค่าธรรมเนียมการโอนเงินคืน",
      ],
    },
  },
  en: {
    //game card
    playNow: "Play Now",
    viewDetails: "View Details",
    startFrom: "Start from",
    availablePackages: "Available Packages",
    package: "Package",
    price: "Price",
    buyNow: "Buy Now",

    // Footer
    footerAboutUs: "About Us",
    footerAboutDesc: "CYBERPAY is a trusted platform for game top-up and online item purchase. Fast and secure service.",
    footerContact: "Contact",
    footerEmailLabel: "Email",
    footerTelLabel: "Tel",
    footerPaymentMethods: "Payment Methods",
    footerBankTransfer: "Bank Transfer",
    footerCreditCard: "Credit/Debit Card",
    footerLegalSocial: "Legal & Social",
    footerTerms: "Terms of Service",
    footerPrivacy: "Privacy Policy",
    footerTrueMoney: "TrueMoney Wallet",
    footerPromptPay: "PromptPay",
    // Header
    headerHome: "Home",
    headerGames: "Games",
    headerTopUp: "Top-up",
    headerVip: "VIP",
    headerSupport: "Support",
    // search page
    search: "Search games...",
    noGamesFound: "No games found matching your search",

    // Common
    platform: "#1 Game Top-up Platform",
    fast: "Fast",
    fastDesc: "Receive items in 1-5 minutes",
    safe: "100% Safe",
    safeDesc: "High security system",
    support: "Support",
    supportDesc: "Our team is ready to help",
    always: "24/7",
    alwaysDesc: "Service available 24/7",
    showMore: "Show more",
    Success: "Success!",
    Topupinfo: "ข้อมูลการเติมเงิน",
    Choosepackage: "เลือกแพ็กเกจที่ต้องการ",
    
    // Game Top-up Page
    loadingGame: "Loading game...",
    gameNotFound: "Game not found",
    failedLoadGame: "Failed to load game",
    pleaseSelectPackage: "Please select a package",
    emailRequired: "Email is required for e-receipt",
    invalidEmail: "Please enter a valid email address",
    failedCreateOrder: "Failed to create order",
    orderCreatedSuccess: "Your order has been created successfully",
    goToAccount: "Go to Account",
    orderType: "Order Type",
    alreadyLoggedIn: "✓ Logged in",
    buyWithoutLogin: "Buy without logging in",
    switchToMember: "Switch to member form",
    discountCoupon: "Discount Coupon",
    enterCouponCode: "Enter coupon code",
    useCoupon: "Use",
    applyCouponSuccess: "✓ Applied coupon {code}, save {discount}%",
    tryCoupons: "Try: SAVE10, SAVE20, WELCOME",
    orderSummary: "Order Summary",
    selectedPackage: "Selected Package",
    noSelection: "No selection yet",
    priceLabel: "Price:",
    discountLabel: "Discount ({discount}%):",
    totalLabel: "Total:",
    emailForReceipt: "Email for Receipt",
    receiptNote: "Receipt will be sent to this email",
    orderButton: "Order",
    processing: "Processing...",
    selectPackageHint: "Click select package to start ordering",
    enterCouponError: "Please enter a coupon code",
    invalidCouponError: "Invalid coupon code",
    needAtLeastFields: "Please fill in all required fields",

    Topup: "Top-up",
    
    login: "Login",
    register: "Register",
    noAccount: "Don't have an account?",
    forgot: "Forgot password?",
    email: "Email",
    password: "Password",
    divider: "OR",
    google: "Google",
    facebook: "Facebook",
    logoDesc: "Login to top up your game instantly",
    errorEmpty: "Please enter Email and Password",
    errorEmail: "Invalid Email format",
    errorPassword: "Password must be at least 8 characters",
    errorLogin: "Incorrect Email or Password",
    success: "Login successful",
    // Support Page
    supportTitle: "Help Center",
    supportSubtitle: "Find answers yourself or contact our team 24/7",
    faqTitle: "Frequently Asked Questions (FAQ)",
    allCategories: "All",
    noFaqFound: "No questions found in this category",
    videoTitle: "Tutorial Videos",
    videoPlaceholder: "Tutorial videos for top-up and system usage — Coming soon",
    contactTitle: "Contact Support Team",
    contactSubtitle: "If FAQ cannot solve your problem, you can contact our team through the channels below",
    stillHaveQuestion: "Still have questions?",
    createTicket: "Create Ticket",
    // Create Ticket Page
    back: "Back",
    createTicketTitle: "Contact Customer Service",
    selectProblem: "Select Problem Type",
    selectProblemPlaceholder: "Select problem type",
    userId: "Order ID",
    userIdPlaceholder: "",
    userIdHelper: "Order ID received after payment",
    paymentMethod: "Payment Method",
    paymentMethodPlaceholder: "",
    paymentMethodHelper: "Payment method you used during purchase",
    emailPlaceholder: "example@gmail.com",
    emailHelper: "Email you used for registration or can be contacted",
    description: "What's wrong",
    descriptionPlaceholder: "Provide details about what you're experiencing...",
    descriptionHelper: "Please provide additional information that can help us fix the problem. The more details you provide, the faster the resolution will be",
    imageUpload: "Additional Image",
    optional: "(Optional)",
    dragDrop: "Drag and drop image or",
    selectImage: "Select Image",
    supportedFormats: "Supported formats: PNG, JPG, JPEG",
    infoText: "Screenshot of money transfer or user ID in game will help us fix the problem faster",
    submit: "Create Ticket",
    successTitle: "Ticket Created",
    successMessage: "We will review the issue and fix it as soon as possible",
    successSubMessage: "You will receive updates via email",
    viewTicket: "View Ticket",
    backToSupport: "Back to Support",
    fillAllFields: "Please fill in all required fields",
    invalidFileType: "Please upload image files only (PNG, JPG, JPEG)",
    problemTypes: {
      "missing-payment": "Report Missing Payment",
      "incorrect-amount": "Report Incorrect Item Amount",
      "wrong-user-id": "Wrong User ID or Server",
      "payment-gateway": "Payment Gateway Issues",
      "account-issue": "Account Issues",
      "other": "Other",
    },
    // FAQ Categories
    faqCategories: {
      topup: "Top-up",
      payment: "Payment",
      security: "Security",
      vip: "VIP & Promotions",
      problem: "Troubleshooting",
      general: "General",
    },
    // Ticket Listing
    ticketsTitle: "Support Tickets",
    sortNewest: "Newest",
    sortOldest: "Oldest",
    noTickets: "No support tickets yet",
    noTicketsDesc: "When you create a ticket, it will appear here",
    statusInQueue: "In Support Queue",
    statusActive: "Active",
    statusClosed: "Closed",
    createdOn: "Created on",
    // Ticket Detail
    ticketDetail: "Ticket Detail",
    statusLabel: "STATUS",
    typeYourMessage: "Type a message...",
    send: "Send",
    closeTicket: "Close Ticket (Solve)",
    attachments: "Attachments",
    actions: "Actions",
    ticketClosedMsg: "This ticket has been closed",
    ticketClosedDesc: "If you need further assistance, please create a new ticket",
    confirmCloseTitle: "Confirm Close Ticket",
    confirmCloseDesc: "Are you sure you want to close this ticket? This action cannot be undone.",
    confirmClose: "Confirm",
    cancelClose: "Cancel",
    fileTooLarge: "File must be less than 5MB",
    invalidAttachType: "Only .jpg, .png, .pdf files are supported",
    attachFile: "Attach File",
    sidebarMyAccount: "My Account",
    sidebarBalance: "Balance",
    sidebarOrders: "Orders",
    sidebarTickets: "Tickets",
    sidebarSettings: "Settings",
    // Account Overview
    accountOverview: "Account Overview",
    home: "Home",
    myAccount: "My Account",
    currentLevel: "Your Current Level",
    progressLabel: "Upgrade Progress",
    viewVipDetail: "View VIP Details",
    availableBalance: "AVAILABLE BALANCE",
    topUp: "Top Up",
    transfer: "Transfer",
    lastUpdated: "Last updated just now",
    transactionHistory: "Transaction History",
    verified: "VERIFIED",
    // Balance / Top-up Page
    topupProcess: "Top-up Process",
    selectPaymentMethod: "Select Payment Method",
    selectTopupAmount: "Select Top-up Amount",
    customAmountPlaceholder: "Minimum 20.00",
   
    paymentMethodLabel: "Payment Method",
    topupAmountLabel: "Top-up Amount",
    feeLabel: "Fee",
    
    confirmTopup: "Confirm Transaction",
    topupNote: "Your balance will be credited automatically after successful payment. For PromptPay, it may take up to 5 minutes.",
    topupHistory: "Top-up History",
    dateTime: "Date / Time",
    statusSuccess: "Success",
    statusFailed: "Failed",
    // Payment Flow Modal
    qrScanInstruction: (method: string) => `Scan ${method} QR Code below to pay`,
    qrAmount: "Amount",
    qrExpiry: "Expires",
    qrRef: "Reference",
    qrScanHint: "Scan QR to proceed (within the same provider)",
    qrSaveBtn: "Save QR Code",
    qrNote: (method: string) => `Note: Use ${method} QR Code to scan only`,
    qrTimeLeft: "3 minutes remaining to scan QR",
    qrMinimize: "Minimize",
    qrContactSupport: "Contact Support",
    qrPaymentProblem: "If you have payment issues, please",
    processingTitle: "Verifying Payment",
    processingDesc: "System is confirming with bank/provider. May take 10 - 30 seconds.",
    processingWarning: "Please do not close or refresh this page",
    processingRefId: "Reference number",
    paymentSuccessTitle: "Payment Confirmed",
    paymentSuccessDesc: "Transaction successful and is now being processed.",
    successEmailNote: "You will receive an email",
    successEmailNote2: "confirming your order has been dispatched.",
    txItem: "Item",
    txChannel: "Channel",
    txTime: "Transaction Time",
    txRefId: "Reference (Tx ID)",
    txTotalPaid: "Total Paid",
    txTotalDue: "Total Due",
    backToHome: "Back to Home",
    viewReceipt: "View Receipt / Download",
    haveIssue: "Have an issue?",
    failedTitle: "Payment Failed",
    failedDesc: "An error occurred. You can retry or try again later.",
    retryPayment: "Retry Payment",
    contactSupport: "Contact Customer Support",
    promptpayDesc: "Scan QR Code to pay instantly",
    truemoneyDesc: "Pay via mobile application",
    recentOrders: "Recent Orders",
    viewAll: "View All",
    viewAllHistory: "VIEW ALL HISTORY",
    general: "General",
    personalInfo: "Personal Info",
    editProfile: "Edit Profile",
    orderHistory: "Order History",
    searchOrders: "Search orders",
    orderDate: "Date",
    orderName: "Order Name",
    orderId: "Order ID",
    viewDetail: "Details",
    // Order Detail
    backToOrders: "Back to orders",
    orderTitle: "Order",
    orderCreatedAt: "Placed on",
    orderStatusSuccess: "Order Completed",
    orderStatusFailed: "Payment Incomplete",
    orderProductInfo: "Product & Character Info",
    orderTopupDetail: "Top-up Details",
    orderProduct: "Product",
    orderUserId: "User ID (OpenID)",
    orderServer: "Server",
    orderPaymentChannel: "Payment Method Used",
    orderPaymentFailed: "Status: Payment Failed",
    orderVerified: "Order has been verified successfully",
    orderProductPrice: "Product Price",
    orderNetTotal: "Net Total",
    orderNetTotalSuccess: "Net Total (Success)",
    orderCheckTitle: "Verify Order",
    orderCreateTicket: "🎫 Create Ticket with Admin",
    orderCreateTicketNote: "If you didn't receive the item or have an issue",
    orderPendingTitle: "Outstanding Balance",
    orderPendingDesc: "System detected your transfer amount doesn't match. Please contact Admin to submit your slip.",
    orderCreateTicketBtn: "Create Ticket with Admin",
    orderNotFound: "Order not found",
    orderStatusSuccessLabel: "Order Completed",
    orderStatusPending: "Pending",
    vipPrivileges: "VIP & Privileges",
    accountSettings: "Account Settings",
    logout: "Logout",
    // VIP Tier Details
    backToOverview: "Back to Overview",
    yourCurrentLevel: "Your Current Level",
    vipTierDetails: "VIP TIER DETAILS",
    statusOverview: "STATUS OVERVIEW",
    highestRank: "HIGHEST RANK",
    infoHighest: "🏆 You are at the highest rank. All privileges are active.",
    infoLower: (tier: string) => `✅ You already have ${tier} privileges.`,
    infoNeedDiamonds: (amount: string, tier: string) =>
      `💎 You need ${amount} more Diamonds to reach ${tier} and unlock more privileges.`,
    allTierDetails: "All Tier Details",
    tierBenefits: "Tier Benefits",
    tierCondition: "Tier Condition",
    minDiamondsText: (amount: string) => `Accumulate at least ${amount} Diamonds to reach this tier.`,
    nextTierText: (amount: string) => `Upgrade to next tier at ${amount} Diamonds.`,
    // VIP Benefits
    vipBenefits: {
      vip1: [
        "2% discount on every top-up",
        "5% bonus Diamonds when topping up ฿100+",
        "Promotion alerts via email",
      ],
      vip2: [
        "5% discount on every top-up",
        "10% bonus Diamonds when topping up ฿100+",
        "Priority Support (response within 2 hrs)",
        "Early access to exclusive promotions",
      ],
      vip3: [
        "10% discount on every top-up",
        "20% bonus Diamonds when topping up ฿100+",
        "VIP Support (response within 30 min)",
        "First access to exclusive items & promotions",
        "Monthly special rewards",
        "No refund processing fee",
      ],
    },
  }
};

const LanguageContext = createContext({
  lang: "th" as Lang,
  setLang: (l: Lang) => { },
  t: translations.th,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("th");
  const t = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
